### ISSUE TITLE
Extracted CSS in v1.1.3 is very different from that extracted in v1.1.2 usign local file in url parameter(file://)

### ISSUE THREAD

**Issue by topogigiovanni** [pocketjoso/penthouse#204]
I'm having very different results after update to v1.1.3. The generated file is considerably different and smaller.

I also noticed is the screenshot can not parse HTML when the url parameter contains a file (file: //)

Below, we have the result of the screenshot of the same code using different versions of the Penthouse.

My Node version is v6.10.3

in v1.1.2
![screenshot-v1-1-2](https://user-images.githubusercontent.com/5891618/33367738-b2140c34-d4d6-11e7-99ff-fd2f7b114a5e.jpg)

in v1.1.3
![screenshot-v1-1-3](https://user-images.githubusercontent.com/5891618/33367750-beae7b00-d4d6-11e7-91f1-a52e9251d4cd.jpg)

**Comment by pocketjoso** [comment]
Hi Giovanni,
Where did you get the second screenshot from? that looks like html, which if that's what you're seeing in your browser should have nothing to do with whether you are using critical css or not.

Do you have a public url for your site that I can test with myself?

**Comment by Saturate** [comment]
For me it seems like puppeteer opens the correct file, but views it a html. Pretty strange, I did not happen when I tested the bump of puppeteer to 0.13, but happens on a fresh install.

**Comment by Saturate** [comment]
Here is a screen capture, the one opens by the API is just HTML. The other one is one I opened. It's opened in `headless: false` mode.

![bug](https://user-images.githubusercontent.com/453018/33377251-17cba0ac-d511-11e7-82fe-eb68e577432d.gif)

**Comment by topogigiovanni** [comment]
Hey guys,
What's happening here is the same thing that @Saturate has shown. But I'm not testing directly on the Puppeteer. But apparently the Puppeteer is not being able to interpret the HTML correctly even coming from a file, causing the error of the extraction of the critical CSS.

I published the tests I'm doing here https://github.com/topogigiovanni/penthouse-diff
remembering that I'm using version 6.10.3 of the Node

**Comment by Saturate** [comment]
I tried running it on puppeteer directly with the following code, and it works:

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        waitUntil: 'networkidle2',
        ignoreHTTPSErrors: true,
        args: ['--disable-setuid-sandbox', '--no-sandbox'],
        headless: false
    });
    const page = await browser.newPage();
    await page.goto('file://C:\\Projects\\testing\\site\\index.html');
    await page.screenshot({path: 'example.png'});

    await browser.close();
})();
```

However I still have a problem that unique to my machine, it never takes the screenshot as goto never ends, for some reason.

**Comment by topogigiovanni** [comment]
Really running the direct puppeteer it works. I did the following test using the version 0.12.0 and 0.13.0 with screenshot successfully . This makes the problem more interesting.

(I'm not using async / await due to my old version of the node)

```javascript
const puppeteer = require('puppeteer');

const URL = 'file:///E:/LABS/critical-test-2/base.index.html';

puppeteer.launch({
		waitUntil: 'networkidle2',
		ignoreHTTPSErrors: true,
		args: ['--disable-setuid-sandbox', '--no-sandbox']
	})
	.then(function(browser) {
		browser
			.newPage()
			.then((page) => {
				page.goto(URL)
					.then(() => {
						page.screenshot({
								path: 'example.png'
							})
							.then(() => {
								browser.close();
							});
					});
			});

		return browser;
	});

```

**Comment by Saturate** [comment]
What windows version are you running?

**Comment by topogigiovanni** [comment]
OS Name: Microsoft Windows 10 Pro
Version: 10.0.14393 Build 14393
System Type: x64-based PC
Processor: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz, 2934 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date:	American Megatrends Inc. 0405, 7/5/2010

**Comment by pocketjoso** [comment]
Confirming, `Penthouse@1.1.3` is broken. #203 did not update the `yarn.lock` file, so CI tests continued to run on `puppeteer 0.12.0` as in the previous penthouse version - that's the only reason the continued to work.

I taking a quick look tonight, but I'm considering reverting the puppeteer upgrade until we have a fix for this problem.

**Comment by pocketjoso** [comment]
Seems to only effect the `file://` protocol.

**Comment by pocketjoso** [comment]
So @topogigiovanni and @Saturate if this is blocking you for now, you can work around it by hosting your html files and avoid accessing them over the `file` protocol. I will continue to debug whether it's possible to have it work again with the latest puppeteer version - perhaps related: https://github.com/GoogleChrome/puppeteer/issues/1472

**Comment by pocketjoso** [comment]
Raised an issue, not much I can do from penthouse until it's fixed in puppeteer:
https://github.com/GoogleChrome/puppeteer/issues/1506

**Comment by Saturate** [comment]
Thanks @pocketjoso I might take a look at it in puppeteer - but I guess it's a hard one to crack.

**Comment by pocketjoso** [comment]
FYI I have now downgraded puppeteer to `0.12.0` again, in `penthouse@1.1.4`. Will revert and upgrade again as soon as there's a fix for this.

**Comment by topogigiovanni** [comment]
Thanks @pocketjoso!

**Comment by Saturate** [comment]
It seems that this has been fixed downstream, in chromium. I'll check up on it a bit later.

**Comment by Saturate** [comment]
This seems to work now, as I stated in https://github.com/GoogleChrome/puppeteer/issues/1506#issuecomment-368004841 if someone could validate that I'm correct please do, and we can bump the version.

**Comment by pocketjoso** [comment]
Well Puppeteer@master still uses an older version, no? So we either wait until the next puppeteer release, or we could update and just add a temporary entry in the README with info on how to manually resolve this issue (use latest Chromium with your puppeteer, or downgrade Penthouse/puppeteer).

**Comment by pocketjoso** [comment]
> ..fixed downstream, in chromium

That would be _upstream_ I think ;) Guess it depends on how you visualise it, but at least with the common dependency parlance.

**Comment by Saturate** [comment]
You might be right with the up or downstream. I tested it with puppeteer `1.1.0`, it has been updated there, so it should already work:

https://github.com/GoogleChrome/puppeteer/releases/tag/v1.1.0

**Comment by pocketjoso** [comment]
This is working in the the current latest Penthouse version.
